name: app_dsi_pedido
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localization: ^0.3.3
  flutter_riverpod: ^3.0.3
  formz: ^0.8.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  image_picker: ^1.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  dotenv: ^4.2.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
